# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.plymouth = {
    enable = true;
    # themePackages = [ pkgs.mikuboot ];
    # theme = "mikuboot";
    # theme = "breeze";
    # theme = "rings"; # Consider themes in the future?
  };
  boot.kernelPackages = pkgs.linuxPackages_cachyos;
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "thunderbolt"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "dm-snapshot"
    "cryptd"
    "nvidia"
    "nvidia_modeset"
    "nvidia_uvm"
    "nvidia_drm"
  ];
  boot.blacklistedKernelModules = [
    "i915"
    "amdgpu"
    "nouveau"
    "iTCO_wdt"
    "nvidiafb"
    "rivafb"
    "rivatv"
    "vga16fb"
  ];
  boot.extraModulePackages = [ config.boot.kernelPackages.nvidiaPackages.latest ];
  # define LUKS device
  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-label/cryptlvm";
  boot.kernelModules = [
    "kvm-amd"
  ];
  # boot.extraModulePackages = with config.boot.kernelPackages; [ r8125 ];
  boot.loader.systemd-boot.consoleMode = "max";
  boot.initrd.systemd.enable = true;
  boot.supportedFilesystems = [ "ntfs" ];
  boot.extraModprobeConfig = ''
    softdep nvidia pre: vfio vfio_pci
    options snd-hda-intel model=alc4080
    options snd-usb-audio model=alc4080
    options nvidia NVreg_UsePageAttributeTable=1 NVreg_RegistryDwords=RMUseSwI2c=0x01;RMI2cSpeed=100
    options nvidia_drm modeset=1
  '';

  # Silent Boot
  boot.consoleLogLevel = 3;
  boot.initrd.verbose = false;
  boot.kernelParams = [
    "quiet"
    # "loglevel=0"
    "splash"
    # "plymouth.use-simpledrm=0"
    # "console=tty0"
    # "console=tty7"
    # "plymouth.nolog"
    "boot.shell_on_fail"
    "udev.log_priority=3"
    "rd.systemd.show_status=auto"
    "systemd.show_status=auto"
    "nvidia.modeset=1"
    "nvidia_drm.modeset=1"
    "nvidia_drm.fbdev=1"
    "rd.udev.log_level=0"
    "rd.driver.blacklist=nouveau"
    "vt.global_cursor_default=0"
  ];
  boot.loader.timeout = 0;
  console = {
    # enable = lib.mkForce false; # Turn off console to keep silent boot when using sddm (not ideal)
    useXkbConfig = true;
    earlySetup = true;
  };

  nixpkgs.config.nvidia.acceptLicense = true;
  services.xserver.videoDrivers = [ "nvidia" ];

  environment.variables = {
    GBM_BACKEND = "nvidia-drm";
    LIBVA_DRIVER_NAME = "nvidia";
    __GLX_VENDOR_LIBRARY_NAME = "nvidia";
    __EGL_VENDOR_LIBRARY_FILENAMES = "${config.hardware.nvidia.package}/share/glvnd/egl_vendor.d/10_nvidia.json";
    # New Trying to Improve performance
    GBM_BACKENDS_PATH = "/run/opengl-driver/lib/gbm";
    __GL_THREADED_OPTIMIZATION = "1";
    __GL_SHADER_CACHE = "1";
    WLR_BACKEND = "vulkan";
    XDG_SESSION_TYPE = "wayland";
    CLUTTER_BACKEND = "wayland";
    WLR_DRM_DEVICES = "/dev/dri/card1:/dev/dri/card0";
    VK_DRIVER_FILES = "/run/opengl-driver/share/vulkan/icd.d/nvidia_icd.x86_64.json";
    # __GL_SHADER_DISK_CACHE="1";
    # __GL_SHADER_DISK_CACHE_PATH="/tmp";
    # __GL_SYNC_TO_VBLANK="1";
    # LD_LIBRARY_PATH = LD_LIBRARY_PATH ++ "/run/opengl-driver/lib:/run/opengl-driver-32/lib";
  };

  environment.systemPackages = with pkgs; [
    linux-firmware
    sof-firmware
    vulkan-loader
    vulkan-validation-layers
    vulkan-tools
    mesa
    virtualgl
    # Test
    alsa-oss
    alsa-lib
    alsa-utils
    alsa-tools
    alsa-plugins
  ];

  hardware = {
    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [
        nvidia-vaapi-driver
        vaapiVdpau
        libvdpau-va-gl
        libva-utils
        vdpauinfo
        egl-wayland
        eglexternalplatform
        wayland
        wgpu-utils
        libglvnd
        # nvtop
        nvitop
        libGL
        glxinfo
        clinfo
      ];
    };
    nvidia = {
      modesetting.enable = true;
      powerManagement.enable = true;
      forceFullCompositionPipeline = true;
      # nvidiaPersistenced = true;
      # powerManagement.finegrained = true;
      open = true;
      package = config.boot.kernelPackages.nvidiaPackages.latest;
      nvidiaSettings = true;
      # prime = {
      #   offload = {
      #     enable = true;
      #     enableOffloadCmd = true;
      #   };
      #   # Make sure to use the correct Bus ID values for your system!
      #   # intelBusId = "PCI:0:2:0";
      #   nvidiaBusId = "PCI:1:0:0";
      #   amdgpuBusId = "PCI:79:0:0";
      # };
    };
  };
  hardware.nvidia-container-toolkit.enable = true;

  fileSystems."/" =
    {
      device = "/dev/disk/by-label/ROOT";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/windows" =
    {
      device = "/dev/disk/by-uuid/F0AEE989AEE948A4";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" ];
    };

  swapDevices = [{
    device = "/swap/swapfile";
    size = 16 * 1024; # 16GB
  }];

  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly";
    fileSystems = [ "/" ];
  };

  fileSystems = {
    "/".options = [ "compress=zstd" "noatime" ];
  };


  # Fstrim
  services.fstrim.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableAllFirmware = true;
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  nix.settings.max-jobs = 16;
  nix.settings.cores = 16;
}
