{ config, lib, pkgs, inputs, ... }:
{
  wayland.windowManager.hyprland = {
    enable = true;
    systemd = {
      enable = false;
      variables = [ "--all" ];
    };
    # package = inputs.hyprland.packages.${pkgs.system}.hyprland;
    plugins = [
      # inputs.hyprland-plugins.packages.${pkgs.system}.hyprexpo
      # inputs.hypr-dynamic-cursors.packages.${pkgs.system}.hypr-dynamic-cursors
      pkgs.hyprlandPlugins.hyprexpo
      pkgs.hyprlandPlugins.hypr-dynamic-cursors
      (pkgs.callPackage ../../../../packages/csd-titlebar-move/plugin.nix {
        # hyprland = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
      })
    ];
    extraConfig = ''
      # #######################################################################################
      # AUTOGENERATED HYPRLAND CONFIG.
      # EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
      # #######################################################################################

      # autogenerated = 1 # remove this line to remove the warning

      # This is an example Hyprland config file.
      # Refer to the wiki for more information.
      # https://wiki.hyprland.org/Configuring/

      # Please note not all available settings / options are set here.
      # For a full list, see the wiki

      # You can split this configuration into multiple files
      # Create your files separately and then link them to this file like this:
      # source = ~/.config/hypr/myColors.conf


      ################
      ### MONITORS ###
      ################

      # See https://wiki.hyprland.org/Configuring/Monitors/
          monitor=,preferred,auto,auto


      ###################
      ### MY PROGRAMS ###
      ###################

      # See https://wiki.hyprland.org/Configuring/Keywords/

      # Set programs that you use
          $terminal = ghostty
          $fileManager = nautilus
      # $menu = wofi --show drun
          $menu = fuzzel


      #################
      ### AUTOSTART ###
      #################

      # Autostart necessary processes (like notifications daemons, status bars, etc.)
      # Or execute your favorite apps at launch like this:

          # exec-once = qs -c caelestia
          exec-once = __GL_THREADED_OPTIMIZATIONS=0 linux-wallpaperengine 2809770238 --silent --screen-root DP-1
          exec-once = hyprctl setcursor Adwaita 24
      # exec-once = nm-applet &
      # exec-once = waybar & hyprpaper & firefox


      #############################
      ### ENVIRONMENT VARIABLES ###
      #############################

      # See https://wiki.hyprland.org/Configuring/Environment-variables/

          env = XCURSOR_THEME,Adwaita
          env = XCURSOR_SIZE,24
          env = HYPRCURSOR_THEME,Adwaita
          env = HYPRCURSOR_SIZE,24


      ###################
      ### PERMISSIONS ###
      ###################

      # See https://wiki.hyprland.org/Configuring/Permissions/
      # Please note permission changes here require a Hyprland restart and are not applied on-the-fly
      # for security reasons

      # ecosystem {
      #   enforce_permissions = 1
      # }

      # permission = /usr/(bin|local/bin)/grim, screencopy, allow
      # permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
      # permission = /usr/(bin|local/bin)/hyprpm, plugin, allow


      #####################
      ### LOOK AND FEEL ###
      #####################

      # Refer to https://wiki.hyprland.org/Configuring/Variables/

      # https://wiki.hyprland.org/Configuring/Variables/#general
          general {
              gaps_in = 5
              gaps_out = 20

              border_size = 2

              # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
              col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
              col.inactive_border = rgba(595959aa)

              # Set to true enable resizing windows by clicking and dragging on borders and gaps
              resize_on_border = true

              # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
              allow_tearing = true

              layout = dwindle
          }

      # https://wiki.hyprland.org/Configuring/Variables/#decoration
          decoration {
              rounding = 10
              rounding_power = 2

              # Change transparency of focused and unfocused windows
              active_opacity = 1.0
              inactive_opacity = 1.0

              shadow {
                  enabled = true
                  range = 4
                  render_power = 3
                  color = rgba(1a1a1aee)
              }

              # https://wiki.hyprland.org/Configuring/Variables/#blur
              blur {
                  enabled = true
                  size = 3
                  passes = 3

                  vibrancy = 0.105
              }
          }

      # https://wiki.hyprland.org/Configuring/Variables/#animations
          animations {
              enabled = yes, please :)

              # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

              bezier = easeOutQuint,0.23,1,0.32,1
              bezier = easeInOutCubic,0.65,0.05,0.36,1
              bezier = linear,0,0,1,1
              bezier = almostLinear,0.5,0.5,0.75,1.0
              bezier = quick,0.15,0,0.1,1

              animation = global, 1, 10, default
              animation = border, 1, 5.39, easeOutQuint
              animation = windows, 1, 4.79, easeOutQuint
              animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
              animation = windowsOut, 1, 1.49, linear, popin 87%
              animation = fadeIn, 1, 1.73, almostLinear
              animation = fadeOut, 1, 1.46, almostLinear
              animation = fade, 1, 3.03, quick
              animation = layers, 1, 3.81, easeOutQuint
              animation = layersIn, 1, 4, easeOutQuint, fade
              animation = layersOut, 1, 1.5, linear, fade
              animation = fadeLayersIn, 1, 1.79, almostLinear
              animation = fadeLayersOut, 1, 1.39, almostLinear
              animation = workspaces, 1, 1.94, almostLinear, fade
              animation = workspacesIn, 1, 1.21, almostLinear, fade
              animation = workspacesOut, 1, 1.94, almostLinear, fade
          }

      # Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
      # "Smart gaps" / "No gaps when only"
      # uncomment all if you wish to use that.
      # workspace = w[tv1], gapsout:0, gapsin:0
      # workspace = f[1], gapsout:0, gapsin:0
      # windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
      # windowrule = rounding 0, floating:0, onworkspace:w[tv1]
      # windowrule = bordersize 0, floating:0, onworkspace:f[1]
      # windowrule = rounding 0, floating:0, onworkspace:f[1]
      windowrule = opacity 0.99999 override, class:zen*

      # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
          dwindle {
              pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
              preserve_split = true # You probably want this
          }

      # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
          # master {
          #     new_status = master
          # }

      # https://wiki.hyprland.org/Configuring/Variables/#misc
          misc {
              force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
              disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
          }


      #############
      ### INPUT ###
      #############

      # https://wiki.hyprland.org/Configuring/Variables/#input
          input {
              kb_layout = us
              kb_variant =
              kb_model =
              kb_options =
              kb_rules =

              follow_mouse = 2
              accel_profile = flat

              sensitivity = 0.3 # -1.0 - 1.0, 0 means no modification.

              touchpad {
                  natural_scroll = false
              }
          }

      # https://wiki.hyprland.org/Configuring/Variables/#gestures
          gestures {
              workspace_swipe = false
          }


      ###################
      ### KEYBINDINGS ###
      ###################

      # See https://wiki.hyprland.org/Configuring/Keywords/
          $mainMod = SUPER # Sets "Windows" key as main modifier

      # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
          bind = $mainMod, Q, exec, $terminal
          bind = $mainMod, C, killactive,
          bind = $mainMod, M, exit,
          bind = $mainMod, E, exec, $fileManager
          bind = $mainMod, V, togglefloating,
          bind = $mainMod, R, exec, $menu
          bind = $mainMod, P, pseudo, # dwindle
          bind = $mainMod, J, togglesplit, # dwindle
          bind = $mainMod, tab, hyprexpo:expo, toggle
          bind = $mainMod, L, exec, hyprlock

      # Move focus with mainMod + arrow keys
          bind = $mainMod, left, movefocus, l
          bind = $mainMod, right, movefocus, r
          bind = $mainMod, up, movefocus, u
          bind = $mainMod, down, movefocus, d

      # Switch workspaces with mainMod + [0-9]
          bind = $mainMod, 1, workspace, 1
          bind = $mainMod, 2, workspace, 2
          bind = $mainMod, 3, workspace, 3
          bind = $mainMod, 4, workspace, 4
          bind = $mainMod, 5, workspace, 5
          bind = $mainMod, 6, workspace, 6
          bind = $mainMod, 7, workspace, 7
          bind = $mainMod, 8, workspace, 8
          bind = $mainMod, 9, workspace, 9
          bind = $mainMod, 0, workspace, 10

      # Move active window to a workspace with mainMod + SHIFT + [0-9]
          bind = $mainMod SHIFT, 1, movetoworkspace, 1
          bind = $mainMod SHIFT, 2, movetoworkspace, 2
          bind = $mainMod SHIFT, 3, movetoworkspace, 3
          bind = $mainMod SHIFT, 4, movetoworkspace, 4
          bind = $mainMod SHIFT, 5, movetoworkspace, 5
          bind = $mainMod SHIFT, 6, movetoworkspace, 6
          bind = $mainMod SHIFT, 7, movetoworkspace, 7
          bind = $mainMod SHIFT, 8, movetoworkspace, 8
          bind = $mainMod SHIFT, 9, movetoworkspace, 9
          bind = $mainMod SHIFT, 0, movetoworkspace, 10

      # Example special workspace (scratchpad)
          bind = $mainMod, S, togglespecialworkspace, magic
          bind = $mainMod SHIFT, S, movetoworkspace, special:magic

      # Scroll through existing workspaces with mainMod + scroll
          bind = $mainMod, mouse_down, workspace, e+1
          bind = $mainMod, mouse_up, workspace, e-1

      # Move/resize windows with mainMod + LMB/RMB and dragging
          bindm = $mainMod, mouse:272, movewindow
          bindm = $mainMod, mouse:273, resizewindow

      # Laptop multimedia keys for volume and LCD brightness
          bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
          bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
          bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
          bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
          bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
          bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

      # Requires playerctl
          bindl = , XF86AudioNext, exec, playerctl next
          bindl = , XF86AudioPause, exec, playerctl play-pause
          bindl = , XF86AudioPlay, exec, playerctl play-pause
          bindl = , XF86AudioPrev, exec, playerctl previous

          bind = $mainMod, Space, global, caelestia:launcher

          # exec = hyprctl dispatch submap global
          # submap = global

      # bindi = Super, Space, global, caelestia:launcher
      # bindin = Super, catchall, global, caelestia:launcherInterrupt
          # bindin = Super, mouse:272, global, caelestia:launcherInterrupt
          # bindin = Super, mouse:273, global, caelestia:launcherInterrupt
          # bindin = Super, mouse:274, global, caelestia:launcherInterrupt
          # bindin = Super, mouse:275, global, caelestia:launcherInterrupt
          # bindin = Super, mouse:276, global, caelestia:launcherInterrupt
          # bindin = Super, mouse:277, global, caelestia:launcherInterrupt
          # bindin = Super, mouse_up, global, caelestia:launcherInterrupt
          # bindin = Super, mouse_down, global, caelestia:launcherInterrupt

      ##############################
      ### WINDOWS AND WORKSPACES ###
      ##############################

      # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
      # See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

      # Example windowrule
      # windowrule = float,class:^(kitty)$,title:^(kitty)$

      # Ignore maximize requests from apps. You'll probably like this.
          windowrule = suppressevent maximize, class:.*

      # Fix some dragging issues with XWayland
          windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

      # Float Windows by default
          windowrulev2 = float, class:.*

      # Set zen size
      windowrulev2 = size 1200 800, class:^(.*zen.*)$

      # Snap Windows
          general:snap {
            enabled = true
            window_gap = 25 # pixels
            monitor_gap = 10 # pixels
          }

      # Plugins
          plugin:dynamic-cursors {

        # enables the plugin
        enabled = true

        # sets the cursor behaviour, supports these values:
        # tilt    - tilt the cursor based on x-velocity
        # rotate  - rotate the cursor based on movement direction
        # stretch - stretch the cursor shape based on direction and velocity
        # none    - do not change the cursors behaviour
        mode = tilt

        # minimum angle difference in degrees after which the shape is changed
        # smaller values are smoother, but more expensive for hw cursors
        threshold = 2

        # override the mode behaviour per shape
        # this is a keyword and can be repeated many times
        # by default, there are no rules added
        # see the dedicated `shape rules` section below!

        # for mode = rotate
        rotate {

            # length in px of the simulated stick used to rotate the cursor
            # most realistic if this is your actual cursor size
            length = 20

            # clockwise offset applied to the angle in degrees
            # this will apply to ALL shapes
            offset = 0.0
        }

        # for mode = tilt
        tilt {

            # controls how powerful the tilt is, the lower, the more power
            # this value controls at which speed (px/s) the full tilt is reached
            # the full tilt being 60° in both directions
            limit = 5000

            # relationship between speed and tilt, supports these values:
            # linear             - a linear function is used
            # quadratic          - a quadratic function is used (most realistic to actual air drag)
            # negative_quadratic - negative version of the quadratic one, feels more aggressive
            # see `activation` in `src/mode/utils.cpp` for how exactly the calculation is done
            function = negative_quadratic

            # time window (ms) over which the speed is calculated
            # higher values will make slow motions smoother but more delayed
            window = 100
        }

        # for mode = stretch
        stretch {

            # controls how much the cursor is stretched
            # this value controls at which speed (px/s) the full stretch is reached
            # the full stretch being twice the original length
            limit = 3000

            # relationship between speed and stretch amount, supports these values:
            # linear             - a linear function is used
            # quadratic          - a quadratic function is used
            # negative_quadratic - negative version of the quadratic one, feels more aggressive
            # see `activation` in `src/mode/utils.cpp` for how exactly the calculation is done
            function = quadratic

            # time window (ms) over which the speed is calculated
            # higher values will make slow motions smoother but more delayed
            window = 100
        }

        # configure shake to find
        # magnifies the cursor if its is being shaken
        shake {

            # enables shake to find
            enabled = true

            # use nearest-neighbour (pixelated) scaling when shaking
            # may look weird when effects are enabled
            nearest = false

            # controls how soon a shake is detected
            # lower values mean sooner
            threshold = 6.0

            # magnification level immediately after shake start
            base = 4.0
            # magnification increase per second when continuing to shake
            speed = 4.0
            # how much the speed is influenced by the current shake intensitiy
            influence = 0.0

            # maximal magnification the cursor can reach
            # values below 1 disable the limit (e.g. 0)
            limit = 0.0

            # time in millseconds the cursor will stay magnified after a shake has ended
            timeout = 1000

            # show cursor behaviour `tilt`, `rotate`, etc. while shaking
            effects = true

            # enable ipc events for shake
            # see the `ipc` section below
            ipc = false
        }

        # use hyprcursor to get a higher resolution texture when the cursor is magnified
        # see the `hyprcursor` section below
        hyprcursor {

            # use nearest-neighbour (pixelated) scaling when magnifing beyond texture size
            # this will also have effect without hyprcursor support being enabled
            # 0 / false - never use pixelated scaling
            # 1 / true  - use pixelated when no highres image
            # 2         - always use pixleated scaling
            nearest = true

            # enable dedicated hyprcursor support
            enabled = true

            # resolution in pixels to load the magnified shapes at
            # be warned that loading a very high-resolution image will take a long time and might impact memory consumption
            # -1 means we use [normal cursor size] * [shake:base option]
            resolution = -1

            # shape to use when clientside cursors are being magnified
            # see the shape-name property of shape rules for possible names
            # specifying clientside will use the actual shape, but will be pixelated
            fallback = clientside
          }
        }

      # Hyprexpo
      plugin {
          hyprexpo {
              columns = 3
              gap_size = 5
              bg_col = rgb(111111)
              workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1

              enable_gesture = true # laptop touchpad
              gesture_fingers = 3  # 3 or 4
              gesture_distance = 300 # how far is the "max"
              gesture_positive = true # positive = swipe down. Negative = swipe up.
          }
      }
    '';
  };
  # wayland.windowManager.hyprland.settings = {
  #   "$mod" = "SUPER";
  #   bind =
  #     [
  #       "$mod, T, exec, ghostty"
  #       "$mod, F, exec, firefox"
  #       ", Print, exec, grimblast copy area"
  #     ]
  #     ++ (
  #       # workspaces
  #       # binds $mod + [shift +] {1..9} to [move to] workspace {1..9}
  #       builtins.concatLists (builtins.genList
  #         (i:
  #           let ws = i + 1;
  #           in
  #           [
  #             "$mod, code:1${toString i}, workspace, ${toString ws}"
  #             "$mod SHIFT, code:1${toString i}, movetoworkspace, ${toString ws}"
  #           ]
  #         )
  #         9)
  #     );
  # };
}
